{
 "title": "tracing-rust-app",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Requests / min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "span_name:\"HTTP GET /posts\"",
     "timeField": "span_start_timestamp_nanos"
    }
   ]
  },
  {
   "title": "Errors / min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "span_start_timestamp_nanos",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "3",
       "type": "count"
      }
     ],
     "query": "span_name:\"HTTP GET /posts\" AND span_attributes.http.status_code:400",
     "timeField": "span_start_timestamp_nanos"
    },
    {
     "bucketAggs": [
      { "field": "span_start_timestamp_nanos", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "span_name:\"HTTP GET /posts\" AND span_attributes.http.status_code:401",
     "timeField": "span_start_timestamp_nanos"
    },
    {
     "bucketAggs": [
      { "field": "span_start_timestamp_nanos", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "span_name:\"HTTP GET /posts\" AND span_attributes.http.status_code:500",
     "timeField": "span_start_timestamp_nanos"
    },
    {
     "bucketAggs": [
      { "field": "span_start_timestamp_nanos", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "span_name:\"HTTP GET /posts\" AND span_attributes.http.status_code:501",
     "timeField": "span_start_timestamp_nanos"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "span_start_timestamp_nanos", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "span_duration_millis",
       "hide": false,
       "id": "3",
       "settings": {
        "percents": [
         "50",
         "90",
         "95",
         "99"
        ]
       },
       "type": "percentiles"
      },
      { "field": "span_duration_millis", "id": "4", "type": "max" }
     ],
     "query": "span_name:fetch_posts",
     "timeField": "span_start_timestamp_nanos"
    }
   ]
  }
 ]
}